# Generated by Django 3.2.1 on 2021-05-05 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210505_0240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Airticle',
        ),
    ]
