# Generated by Django 3.2.1 on 2021-05-05 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_article_airticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airticle',
            old_name='descirption',
            new_name='description',
        ),
    ]
